name: Sample Archives Generator
run-name: Generating sample archives
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate
        run: ./generate.sh
      - name: Commit changes
        run: |
          git stage -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Generated archive samples"
          git push
